{% set name = "autocommand" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 878de9423c5596491167225c2a455043c3130fb5b7286ac83443d45e74955f34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "from autocommand import autocommand"

about:
  home: https://github.com/Lucretiel/autocommand
  summary: A library to automatically generate and run simple argparse parsers from function signatures.
  description: |
    Autocommand turns a function into a command-line program. It converts 
    the function's parameter signature into command-line arguments, and 
    automatically runs the function if the module was called as ``__main__``.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://github.com/Lucretiel/autocommand
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - carlodri
